#ifndef _LAYOUT_H_H_
#define _LAYOUT_H_H_ 
//Main
#define MAININTERFACE_W 1100
#define MAININTERFACE_H 640

#define MAINI_MULTISTART_W 12
#define MAINI_MULTISTART_H 73

//Multi-Para
#define MULTIPARA_INTERFACE_W 1015  
#define MULTIPARA_INTERFACE_H 725

#define MULTIPARA_TIME_W 150//(MULTIPARA_INTERFACE_W-130)  
#define MULTIPARA_TIME_H (15)

#define MULTIPARA_SPO2WAVE_W (MULTIPARA_INTERFACE_W-250)  
#define MULTIPARA_SPO2WAVE_H (MULTIPARA_INTERFACE_H/7)

#define MULTIPARA_STARTEND_W 1
#define MULTIPARA_STARTEND_H 1//((MULTIPARA_INTERFACE_H - MULTIPARA_SPO2WAVE_H*5)/1.5)

#define MULTIPARA_SPO2INFO_W (MULTIPARA_INTERFACE_W-MULTIPARA_SPO2WAVE_W)  
#define MULTIPARA_SPO2INFO_H MULTIPARA_SPO2WAVE_H

#define MULTIPARA_ECGINFO_W (MULTIPARA_INTERFACE_W - MULTIPARA_SPO2WAVE_W)  
#define MULTIPARA_ECGINFO_H (MULTIPARA_SPO2WAVE_H*1.2)

#define MULTIPARA_RESPINFO_W (MULTIPARA_INTERFACE_W - MULTIPARA_SPO2WAVE_W)  
#define MULTIPARA_RESPINFO_H (MULTIPARA_SPO2WAVE_H*0.8)

#define MULTIPARA_TEMPINFO_W (MULTIPARA_INTERFACE_W - MULTIPARA_SPO2WAVE_W)  
#define MULTIPARA_TEMPINFO_H (MULTIPARA_SPO2WAVE_H*0.9)

#define MULTIPARA_NIBPINFO_W (MULTIPARA_INTERFACE_W - MULTIPARA_SPO2WAVE_W)  
#define MULTIPARA_NIBPINFO_H (MULTIPARA_SPO2WAVE_H*1.1)

//5
#define MULTIPARA_5DECGWAVE_W (MULTIPARA_SPO2WAVE_W/2-1)  
#define MULTIPARA_5DECGWAVE_H MULTIPARA_SPO2WAVE_H
//3
#define MULTIPARA_3DBASE_H (MULTIPARA_INTERFACE_H/4)
#define MULTIPARA_3DECGWAVE_W (MULTIPARA_SPO2WAVE_W)  
#define MULTIPARA_3DECGWAVE_H MULTIPARA_3DBASE_H

/*
#define HEMO_CLIENTVIEW_START_W 10  
#define HEMO_CLIENTVIEW_START_H 130

#define HEMO_CLIENTVIEW_W (MULTIPARA_INTERFACE_W-30)  
#define HEMO_CLIENTVIEW_H (MULTIPARA_INTERFACE_H-170)

#define HEMO_TIMEVIEW_W 130
#define HEMO_TIMEVIEW_H 15
#define HEMO_TIME_START_W (MULTIPARA_INTERFACE_W-HEMO_TIMEVIEW_W-10)  
#define HEMO_TIME_START_H (HEMO_CLIENTVIEW_START_H-HEMO_TIMEVIEW_H)*/

#endif