'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GMed_PM01.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_dropdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-dropdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_dropdown_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-dropdown-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fix_blue_alarm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fix_blue_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fix_HB_sound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fix_HB_sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fix_red_alarm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fix_red_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fix_yellow_alarm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fix_yellow_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_add_patient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-add-patient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_add_patient_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-add-patient-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_alarm_limits() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-alarm-limits", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_alarm_limits_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-alarm-limits-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_alarm_limits1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-alarm-limits1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_auto_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-auto-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_colors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-colors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_colors_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-colors-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_default_setup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-default-setup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_default_setup_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-default-setup-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_default_setup1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-default-setup1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_lamp_brightness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-lamp-brightness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_lamp_brightness_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-lamp-brightness-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_lamp_brightness1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-lamp-brightness1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_manual_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-manual-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_parameter_setup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-parameter-setup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_parameter_setup_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-parameter-setup-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_screen_brightness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-screen-brightness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_screen_brightness_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-screen-brightness-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_screen_setup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-screen-setup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_screen_setup_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-screen-setup-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_sound_level() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-sound-level", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_sound_level_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-sound-level-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_sound_volume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-sound-volume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_sound_volume_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-sound-volume-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_view_patient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-view-patient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sidebar_view_patient_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebar-view-patient-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property splash1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property splash2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property splashscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splashscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_alarm_history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-alarm-history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_alarm_history_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-alarm-history-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_alarm_setup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-alarm-setup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_alarm_setup_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-alarm-setup-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_home_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-home-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_monitor_setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-monitor-setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_monitor_setting_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-monitor-setting-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_nibp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-nibp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_nibp_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-nibp-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_patient_data() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-patient-data", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taskbar_patient_data_activated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskbar-patient-data-activated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
